[package]
name = "lifegame-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"

[dev-dependencies]
criterion = "0.6.0"
rand = "0.9.1"

[[bench]]
name = "benchmark"
harness = false
