[package]
name = "lifegame-tui"
version = "0.1.0"
authors = ["furrymonster <4urrym0nster@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
lifegame-core = { path = "../lifegame-core" }
rand = "0.9.1"
ratatui = "0.29.0"
